/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProjectsRouteImport } from "./routes/projects";

const ProjectsRoute = ProjectsRouteImport.update({
	id: "/projects",
	path: "/projects",
	getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
	IndexRoute: IndexRoute,
	ProjectsRoute: ProjectsRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren);
